name: Generate a build and deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
 #   steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Deploy
       curl -X POST -u https://webhooks.hostinger.com/deploy/ebb4959ed6b93b0f8b7c57455944d4fa

